name: Go

on:
  push:
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Install Prereqs
      run: | 
        apt-get update
        apt-get install -y libayatana-appindicator3-dev libhidapi-hidraw0 libhidapi-dev

    - name: Build
      run: go build -v ./...

#     - name: Test
#       run: go test -v ./...
